section_name:
    width: 43
    font: 'DejaVuSans-Bold'
    font_size: 16
    Y_delta: 15
    color: '#000000'


fonts:
  default: 'DejaVuSans'
  bold: 'DejaVuSans-Bold'
  italic: 'DejaVuSans-Oblique'

sizes:
  subtitle: 16
  normal: 12
  small: 10

colors:
  text: '#000000'
  highlight: '#FFFFFF'
  link: '#0000FF'
  grey_background: '#D3D3D3'
  footer: '#808080'

left_section_name:
    width: 43
    font: 'DejaVuSans-Bold'
    font_size: 10
    Y_delta: 15
    color: '#FFFFFF'

left_email_phone:
  font_size: 10
  color: '#FFFFFF'
  font: 'DejaVuSans'
  width: 43
  Y_delta: 12

left_top_skills:
    width: 43
    font: 'DejaVuSans'
    font_size: 10
    Y_delta: 15
    color: '#FFFFFF'

left_default:
    width: 37
    font: 'DejaVuSans'
    font_size: 10
    Y_delta: 15
    color: '#FFFFFF'

personal_data_info:
  width: 60  # Ustalenie szerokości zawijania tekstu dla personal_data_info
  font: 'DejaVuSans-Oblique'  # Czcionka dla personal_data_info
  font_size: 10  # Rozmiar czcionki dla personal_data_info
  color: '#FF0000'  # Kolor czcionki dla personal_data_info
  y_position: 90
  Y_delta: 13

name_and_surname:
  y_top_minus: 70
  font_size: 24
  color: '#000000'
  font: 'DejaVuSans-Bold'
  width: 43
  Y_delta: 13

summary_short:
  y_top_minus: 95
  width: 50
  font: 'DejaVuSans-Oblique'
  font_size: 12
  color: '#A9A9A9'
  Y_delta: 13

summary:
  y_top_minus: 160
  width: 50
  font: 'DejaVuSans'
  font_size: 12
  color: '#000000'
  Y_delta: 13

experience:
  employer:
    width: 43
    font: 'DejaVuSans-Bold'
    font_size: 12
    Y_delta: 15
    color: '#000000'
  position:
    width: 43
    font: 'DejaVuSans-Oblique'
    font_size: 12
    Y_delta: 13
    color: '#000000'
  period:
    width: 43
    font: 'DejaVuSans'
    font_size: 10
    Y_delta: 12
    color: '#000000'
  location:
    width: 43
    font: 'DejaVuSans-Bold'
    font_size: 10
    Y_delta: 14
    color: '#000000'
  description:
    width: 60
    font: 'DejaVuSans'
    font_size: 10
    Y_delta: 14
    color: '#000000'
  technologies:
    width: 60
    font: 'DejaVuSans-Bold'
    font_size: 9
    Y_delta: 16
    color: '#000000'

linkedin_more_info:
  text: "More information about my experience on my LinkedIn profile:"
  y_position: 70
  font: 'DejaVuSans'
  font_size: 10
  width: 80
  color: '#0000FF'
  Y_delta: 12

courses:
  width: 60
  font: 'DejaVuSans'
  font_size: 10
  Y_delta: 15
  color: '#000000'

education:
  y_top_minus: 70
  Y_delta_after_topic: 20
  school_name:
    width: 43
    font: 'DejaVuSans-Bold'
    font_size: 12
    Y_delta: 13
    color: '#000000'
  degree:
    width: 43
    font: 'DejaVuSans-Oblique'
    font_size: 12
    Y_delta: 13
    color: '#000000'
  years:
    width: 43
    font: 'DejaVuSans-Oblique'
    font_size: 12
    Y_delta: 30
    color: '#000000'

  degree_font_size: 12
  Y_delta_after_entry: 20